<?php
// $Id: field_kaltura.install,v 1.2.4.3 2009/01/14 14:19:36 kaltura Exp $

/*
 * @file
 * Installation process for kaltura CCK field module
 *
 */

/**
 * Implementation of hook_install().
 */
function field_kaltura_install() {
}

/**
 * Implementation of hook_uninstall().
 */
function field_kaltura_uninstall() {
}

/**
 * Implementation of hook_enable().
 */
function field_kaltura_enable() {
}

/**
 * Implementation of hook_disable().
 */
function field_kaltura_disable() {
}